### ISSUE TITLE
Error in distributed_generate_data

### ISSUE THREAD

**Issue by Trulli99** [zubair-irshad/shapo#12]
Hello, when I try to run python prepare_data/distributed_generate_data.py with camera_val or real_val type, I get the following error in the workers generated file:

  0%|          | 0/459 [00:00<?, ?it/s]
  0%|          | 0/459 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "prepare_data/distributed_worker.py", line 45, in <module>
    main(args)
  File "prepare_data/distributed_worker.py", line 28, in main
    annotate_test_data(args.data_dir, 'Real', 'test', args.start, args.end)
  File "D:\shapo\prepare_data\generate_training_data.py", line 451, in annotate_test_data
    img_path.split('/')[-2], img_path.split('/')[-1]))
IndexError: list index out of range

Do you know how can I solve this?
Thank you in advance.

Note: When I run it with camera_train and real_train I don´t have any problem.

**Comment by zubair-irshad** [comment]
Have you downloaded nocs_results as mentioned [here](https://github.com/zubair-irshad/shapo#-dataset) and can confirm that this path indeed exists in your data folder? `results/nocs_results`. Could you also share your directory structure of data folder?

**Comment by Trulli99** [comment]
Yes, I do. This is the directory for that folder  D:\shapo\data\results\nocs_results

**Comment by zubair-irshad** [comment]
Can you share the full directory structure of `nocs_results`? i.e. how the files in their are stored? Also could you print out your `img_path` flag?

**Comment by Trulli99** [comment]
You mean this?
nocs_results
   ├── real_test
   └── val
This is the output of img_path "test\scene_1\0000"

**Comment by Trulli99** [comment]
I was able to solve it. The directory list add the bars to the left '\', and in the code is splitting the img_path string when '/' would be found so I add to change that. Sorry to bother once again.
Thank you!

**Comment by zubair-irshad** [comment]
Makes sense. I guess you were running it on windows machine? The code is setup for ubuntu. Glad to know you were able to solve it.

**Comment by Trulli99** [comment]
Yes, I am

**Comment by Trulli99** [comment]
By the way, I get this warning sometimes.
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject

Do you think it might be because I am using windows? And do you think it might affect something?
Sorry, to be always bothering you

**Comment by zubair-irshad** [comment]
Not sure as I never got this warning when running it locally but looks like something with scipy library version.
