### ISSUE TITLE
I can't find those 4 files:

### ISSUE THREAD

**Issue by lululovecode** [zubair-irshad/shapo#15]
I can't find those 4 files:
could you please update the link for dataset?    
├── camera_val.pkl
    ├── real_train.pkl
    ├── real_test.pkl
    └── mug_meta.pkl

**Comment by zubair-irshad** [comment]
Please see nocs_preprocess_data [here](https://github.com/zubair-irshad/shapo#-dataset). It has those files. 

Here is the [direct link](https://www.dropbox.com/s/8im9fzopo71h6yw/nocs_preprocess.tar.gz?dl=1).
