### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by Trulli99** [zubair-irshad/shapo#6]
Hi, in the Dataset part there is no link to download the zip for auto_encoder_model and in the zip download of sdf_rgb_pretrained I there was no rgb_latent folder.
Thanks for the work!

**Comment by dongho-Han** [comment]
Hello.
I have a same problem too.
Can you update the `auto_encoder_model` and `sdf_rgb_pretrained` files?
Thanks!

**Comment by zubair-irshad** [comment]
Hi @Trulli99 @dongho-Han, 

Thanks for your interest in our work. I have updated the readme with the correct link. Please see the [latest commit](https://github.com/zubair-irshad/shapo/commit/924a48f3d6a58ca2969e420741e304027eb8b759) or pull the latest from the master branch. 

Specifically, the codebase doesn't need `auto_encoder_model` and the correct directory structure should be as [follows](https://github.com/zubair-irshad/shapo#-dataset) which you can get after downloading `sdf_rgb_pretrained` from [here](https://github.com/zubair-irshad/shapo#-dataset). 

Hope it helps and thanks for your patience!
