### ISSUE TITLE
Problems with running code

### ISSUE THREAD

**Issue by dongho-Han** [zubair-irshad/shapo#7]
Hello.
Thanks for the nice work!
I tried to run your 'ShAPO' code, but I got stuck.
Can you share the solution how to solve the problems written below?
1. As mentioned in #6 , there is no `auto_encoder_model` folder and `sdf_rgb_pretained/rgb_latent` folder in supported download link. Can you update the link?

2. When I try to run the distributed script,
```python prepare_data/distributed_generate_data.py --data_dir /home/ubuntu/shapoplusplus/data/nocs_data --type camera_train```
I got an error message like this
FileNotFoundError: [Errno 2] No such file or directory: '/data/sdf_rgb_pretrained/rgb_net_weights/reconstructor.pt'
Because there is no `rgb_net_weights/reconstructor.pt` in $ShAPO_Repo/data.
How to solve this?

3. After download and organize a small Real test subset, pretrained checkpoints,...
directory shape is like this
test_data
├── ckpts
│   └── shapo_real.ckpt
├── Real
│   ├── test
│   │   ├── scene_1
│   │   │   ├── 0006_color.png
│   │   │   └── 0006_depth.png
│   │   ├── scene_2
│   │   │   ├── 0049_color.png
│   │   │   └── 0049_depth.png
│   │   └── scene_3
│   │       ├── 0003_color.png
│   │       └── 0003_depth.png
│   └── test_list_subset.txt
├── sdf_rgb_pretrained
│   ├── all_train_ids.json
│   ├── LatentCodes
│   │   ├── 1000.pth
│   │   ├── 100.pth
│   │   ├── 2000.pth
│   │   ├── 500.pth
│   │   ├── all_train_ids.json
│   │   └── latest.pth
│   ├── Logs.pth
│   ├── ModelParameters
│   │   ├── 1000.pth
│   │   ├── 100.pth
│   │   ├── 2000.pth
│   │   ├── 500.pth
│   │   └── latest.pth
│   ├── OptimizerParameters
│   │   ├── 1000.pth
│   │   ├── 100.pth
│   │   ├── 2000.pth
│   │   ├── 500.pth
│   │   └── latest.pth
│   ├── rgb_net_weights
│   │   ├── feats_colors.pt
│   │   └── reconstructor.pt
│   └── specs.json

It means that there is no `sdf_rgb_pretrained/Reconstructions`, `sdf_rgb_pretrained/rgb_latent` in $ShAPO_Repo/test_data.

Is there any missing points that I'm doing?

4. Also, is there a way to inference with pre-trained weights without training?

Thanks!

**Comment by zubair-irshad** [comment]
Hi @dongho-Han, 

Thanks for your interest in our work. Please see the following answer https://github.com/zubair-irshad/shapo/issues/6#issuecomment-1382195978 for your question 1.2 and 3. 

For question 4. Yes, absolutely. Please see this [notebook](https://colab.research.google.com/github/zubair-irshad/shapo/blob/master/notebook/explore_ShAPO.ipynb) where we demo inference with pretrained weights without re-training. You can also check number 3. [here](https://github.com/zubair-irshad/shapo#-training-and-inference) as we provide a dedicated script [inference_real](https://github.com/zubair-irshad/shapo/blob/master/inference/inference_real.py) here.

Hope it helps!
